// import 'package:HrCabDriver/models/ride_request_model.dart';

// class RideDetailsHelper {
// // ride_helpers.dart
//   Map<String, dynamic> rideRequestToMap(RideRequest ride) {
//     return {
//       'Ride Request ID': ride.rideRequestId,
//       'Booking Number': ride.rideBookingNumber,
//       'User ID': ride.userId,
//       'Pickup Location': ride.pickupLocation,
//       'Pickup City': ride.pickupCity,
//       'Pickup Lat': ride.pickupLat,
//       'Pickup Long': ride.pickupLong,
//       'Drop Location': ride.dropLocation,
//       'Drop City': ride.dropCity,
//       'Drop Lat': ride.dropLat,
//       'Drop Long': ride.dropLong,
//       'Map Image': ride.mapImage,
//       'Total KM': ride.totalKm,
//       'Total Minutes': ride.totalMin,
//       'Approximate Fare': ride.approximateTotalAmount,
//       'Pickup DateTime': ride.pickupDatetime,
//       'Return DateTime': ride.returnDatetime,
//       'Trip Type': ride.tripType,
//       'Booking DateTime': ride.bookingDatetime,
//       'Is Booked': ride.isBooked,
//       'VD Log ID': ride.vdLogId,
//       'Driver ID': ride.driverId,
//       'Vehicle ID': ride.vehicleId,
//       'Segment ID': ride.segmentId,
//       'Assigned Segment ID': ride.assignedSegmentId,
//       'Is Ride Now': ride.isRideNow,
//       'Ride Return Log ID': ride.rideReturnLogId,
//       'Is Deleted': ride.isDeleted,
//       'Is Ride Notified To Driver': ride.isRideNotificationSendToDriver,
//       'Ride Assigned to Admin': ride.rideAssignToAdmin,
//       'SOS Alert': ride.isSosAlert,
//       'SOS By': ride.sosBy,
//       'SOS Lat': ride.sosLat,
//       'SOS Long': ride.sosLong,
//       'Ride Detail ID': ride.rideDetailId,
//       'Ride ID': ride.rideId,
//       'Ride Start Lat': ride.rideStartLat,
//       'Ride Start Long': ride.rideStartLong,
//       'Ride Start Location': ride.rideStartLocation,
//       'Ride Start City': ride.rideStartCity,
//       'Ride End City': ride.rideEndCity,
//       'Start Meter Reading': ride.rideStartMeterReading,
//       'Start Meter Image': ride.rideStartMeterReadingImg,
//       'Ride Start Time': ride.rideStartTime,
//       'Ride End Lat': ride.rideEndLat,
//       'Ride End Long': ride.rideEndLong,
//       'Ride End Location': ride.rideEndLocation,
//       'End Meter Reading': ride.rideEndMeterReading,
//       'End Meter Image': ride.rideEndMeterReadingImg,
//       'Ride End Time': ride.rideEndTime,
//       'Total Ride KM': ride.totalRideKm,
//       'Total Ride Time': ride.totalRideTime,
//       'Total Ride Amount': ride.totalRideAmount,
//       'Amount From Wallet': ride.amountFromWallet,
//       'Ride Completed': ride.rideIsCompleted,
//       'Payment Status': ride.ridePaymentStatus,
//       'Return Trip Needed': ride.driverNeedReturnTrip,
//       'Return Trip City': ride.driverReturnTripCity,
//       'Created On': ride.createdOn,
//       'Trip ID': ride.tripId,
//       'User Name': ride.userFullName,
//       'Driver Name': ride.driverFullName,
//       'Owner Name': ride.ownerFullName,
//       'User Mobile': ride.userMobile,
//       'Driver Mobile': ride.driverMobile,
//       'Owner Mobile': ride.ownerMobile,
//       'Vehicle Image': ride.vehicleImage,
//       'Vehicle Model ID': ride.vehicleModelId,
//       'Registration No': ride.vehicleRegistrationNo,
//       'Remaining Trips': ride.noOfTripRemain,
//       'Chargeable Amount': ride.chargeableAmount,
//       'Trips Given': ride.noOfTripGiven,
//       'Model Name': ride.modelName,
//       'Brand ID': ride.brandId,
//       'Model Image': ride.modelImage,
//       'Brand Name': ride.brandName,
//       'Segment Name': ride.segmentName,
//       'Segment Image': ride.segmentImage,
//       'Driver Review': ride.driverReview,
//       'Driver Rating': ride.driverRating,
//       'Driver Avg Rating': ride.driverAverageRating,
//       'Booking Status': ride.bookingStatus,
//       'Is Return': ride.isReturn == true ? 'Yes' : 'No',
//     };
//   }
// }
